# Site settings
title:  KGD
email: karinaginavan@gmail.com
description: "Karina Ginavan Design"
baseurl: "/kgd" # the subpath of your site, e.g. /blog/
url: "http://karinaginavan.github.io/kgd" # the base hostname & protocol for your site
twitter_username: karinaginavan
github_username:  karinaginavan

# Build settings
markdown: kramdown

goselfstorage: goselfstorage
